In [2]:
import numpy as np


In [5]:
arr_id = np.array([1,2,3,4,5])
print("1D Array",arr_id)


1D Array [1 2 3 4 5]


List vs numpy array


In [3]:
py_List = [1,2,3]
print("Python list multiplication", py_List * 2) 

np_List = np.array([1,2,3])
print("Python array multiplication", np_List * 2)


Python list multiplication [1, 2, 3, 1, 2, 3]
Python array multiplication [2 4 6]


Creating array  from scratch

In [7]:
zeros = np.zeros((3,4))
print("Zeros array: \n",zeros)

ones = np.ones((3,4))
print("Ones array: \n",ones)

full = np.full((2,2),7)
print("full array: \n",full)


random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0,10, 1)
print("sequence array: \n",sequence)






Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.01969093 0.87216851 0.37846883]
 [0.84245977 0.83822054 0.40489578]]
sequence array: 
 [0 1 2 3 4 5 6 7 8 9]


Vector Matrix and Tensor

In [ ]:
vector = np.array([1,2,3])
print("Vector: \n",vector)

matrix = np.array([[1,2,3],
                  [4,5,6]])
print("matrix: \n",matrix)


tensor = np.array([[[1,2],[3,4]],
                   [[5,6], [7,8]]])
print("tensor: \n",tensor)

Vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array properties

In [13]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size", arr.size)
print("Data Type ", arr.dtype)



Shape  (2, 3)
Dimension  2
Size 6
Data Type  int64


Array Reshaping

In [27]:
arr = np.arange(12)
print(" \n Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)


flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose

transpose = reshaped.T
print("\n Transpose Array ", transpose)


 
 Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose Array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
