Numpy Array and Operation

In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing:", arr[2:7])
print("With Step:", arr[1:8:2])
print("Negative indexing:", arr[-3])


Basic Slicing: [3 4 5 6 7]
With Step: [2 4 6 8]
Negative indexing: 8


In [ ]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("Specific Element:", arr_2d[1,2])
print("Entire Row:", arr_2d[1])
print("Column:", arr_2d[:, 0])


Specific Element: 6
Entire Row: [4 5 6]
Entire Row: [1 4 7]


Sorting


In [15]:
unsorted = np.array([1,1,2,3,2,3,4,5,6,7,8,9])
print("Sorted Array" , np.sort(unsorted))

arr_2d_unsorted = np.array([[3 , 1],[1, 2],[ 2, 3] ])
print("Sorted 2d array by column" , np.sort(arr_2d_unsorted, axis=0))


Sorted Array [1 1 2 2 3 3 4 5 6 7 8 9]
Sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]


Filter

In [16]:
number = np.array([1,2,3,4,5,6,7,8,9])
even_number = number[number % 2 == 0]
print("Even Numbers",even_number)

Even Numbers [2 4 6 8]


## Filter with Mask 

In [17]:
mask = number > 5
print("Number Greater then 5 ",number[mask])

Number Greater then 5  [6 7 8 9]


## Fancy Indexing vs  np.where()


In [ ]:
indices = [0 , 2 ,4]
print(number[indices])

where_result = np.where(number > 5)

print("NP where",number[where_result])





[1 3 5]
NP where [6 7 8 9]


In [27]:
condition_array = np.where(number > 5 , number * 2 , number) 
print(condition_array)

[ 1  2  3  4  5 12 14 16 18]


## Adding and Removing Data


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combine = np.concatenate((arr1,arr2))
print(combine)

[1 2 3 4 5 6]


## Array Compatibilty


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
print("Compatibility shapes", arr1.shape == arr2.shape)

Compatibility shapes False


In [34]:
original = np.array([[1,2], [3,4]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)


new_col = np.array([[7], [8]])
with_new_col = np.hstack((original,new_col))
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [36]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("Array After Deletion:" ,deleted)

Array After Deletion: [1 2 4 5]
