Advance Operation with Business Example


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
import numpy as np

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print(sales_data)
print("\n Sales Data Shape", sales_data.shape)
print("\n Sales Data for last 3 restraunt", sales_data[:, 1:])


[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]

 Sales Data Shape (5, 5)

 Sales Data for last 3 restraunt [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [13]:
## total sales per year
print(np.sum(sales_data, axis=0))
yearly_total = np.sum(sales_data[: , 1:],axis=0)
print(yearly_total)


[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
