Advance Operation with Business Example


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [14]:
import numpy as np

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print(sales_data)
print("\n Sales Data Shape", sales_data.shape)
print("\n Sales Data for last 3 restraunt", sales_data[:, 1:])


[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]

 Sales Data Shape (5, 5)

 Sales Data for last 3 restraunt [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


In [19]:

print(np.sum(sales_data, axis=0))
yearly_total = np.sum(sales_data[: ,1:], axis=0)
print(yearly_total)


## Minimum Sales
min_sales = np.min(sales_data[: , 1:],axis=1)
print("Min",min_sales)



[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
Min [150000 120000 200000 180000 160000]


# Maximum Sales Per Year

In [21]:
max_Sales = np.max(sales_data[:,1:],axis=0)
print("Max",max_Sales)

Max [200000 230000 260000 300000]


In [22]:
# Average Sales per Restaurent
avg_sales = np.mean(sales_data[:,1:],axis=1)
print("Avg",avg_sales)

Avg [200000. 152500. 247500. 225000. 195000.]
